# Generated by Django 4.2.2 on 2023-11-10 06:58

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import eshop.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eshop', '0002_auto_20231027_1010'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ایجاد')),
                ('modify_date', models.DateTimeField(auto_now=True, null=True, verbose_name='تاریخ ویرایش')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('uuid', models.CharField(default=eshop.models.create_factor_id, max_length=20, verbose_name='شماره فاکتور')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='قیمت')),
                ('tax', models.PositiveIntegerField(default=0, verbose_name='مالیات')),
                ('value_added_tax', models.PositiveIntegerField(default=0, verbose_name='مالیات بر ارزش افزوده')),
                ('discount_code', models.CharField(default='', max_length=50, verbose_name='کد تخفیف')),
                ('discount_price', models.PositiveIntegerField(default=0, verbose_name='مبلغ تخفیف')),
                ('total_weight', models.PositiveIntegerField(default=0, verbose_name='وزن کل محصولات')),
                ('payment_tracking_code', models.CharField(default='', max_length=255, verbose_name='کد رهگیری پرداخت')),
                ('payment_id', models.PositiveBigIntegerField(default=eshop.models.get_random_payment_id, verbose_name='شماره پرداخت')),
                ('reference_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='کد مرجع')),
                ('sales_reference_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='saled reference ID')),
                ('res_code', models.BigIntegerField(blank=True, null=True, verbose_name='res code')),
                ('payment_date', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ پرداخت')),
                ('final_price', models.PositiveIntegerField(default=0, verbose_name='مبلغ نهایی')),
                ('shipping_cost', models.PositiveIntegerField(default=0, verbose_name='هزینه ارسال')),
                ('shipping_tracking_code', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='کد رهگیری ارسال')),
                ('name_family', models.CharField(max_length=255, verbose_name='نام و نام خانوادگی')),
                ('phone_number', models.CharField(max_length=255, verbose_name='شماره تماس')),
                ('state', models.CharField(max_length=255, verbose_name='استان')),
                ('city', models.CharField(max_length=255, verbose_name='شهر')),
                ('address', models.CharField(max_length=255, verbose_name='آدرس')),
                ('post_code', models.CharField(max_length=255, verbose_name='کد پستی')),
                ('customer_comment', models.CharField(blank=True, max_length=255, null=True, verbose_name='یادداشت مشتری')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eshop.paymentmethod', verbose_name='روش پرداخت')),
                ('payment_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eshop.paymentstatus', verbose_name='وضعیت پرداخت')),
                ('shipping_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eshop.shippingmethod', verbose_name='روش ارسال')),
                ('shipping_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eshop.shippingstatus', verbose_name='وضعیت ارسال')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'فاکتور',
                'verbose_name_plural': 'فاکتور ها',
            },
        ),
        migrations.CreateModel(
            name='FactorItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ایجاد')),
                ('modify_date', models.DateTimeField(auto_now=True, null=True, verbose_name='تاریخ ویرایش')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('product', models.CharField(max_length=255, verbose_name='محصول')),
                ('monetary_option', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='ویژگی پولی محصول')),
                ('count', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='تعداد')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='قیمت')),
                ('factor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eshop.factor', verbose_name='فاکتور')),
            ],
            options={
                'verbose_name': 'آیتم فاکتور',
                'verbose_name_plural': 'آیتم های فاکتور',
            },
        ),
    ]
