# Generated by Django 4.2.2 on 2023-10-27 11:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import eshop.validators
import main.tools


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admin_theme', '0001_initial'),
        ('eshop', '0002_alter_brand_options_alter_cart_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='create date'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='modify_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='modify date'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='create date'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='modify_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='modify date'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاریر'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='create date'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='modify_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='modify date'),
        ),
        migrations.AlterField(
            model_name='category',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='create date'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='modify_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='modify date'),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='create date'),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='modify_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='modify date'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='create date'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='modify_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='modify date'),
        ),
        migrations.AlterField(
            model_name='paymentstatus',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='create date'),
        ),
        migrations.AlterField(
            model_name='paymentstatus',
            name='modify_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='modify date'),
        ),
        migrations.AlterField(
            model_name='product',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='create date'),
        ),
        migrations.AlterField(
            model_name='product',
            name='has_value_added_tax',
            field=models.BooleanField(default=False, verbose_name='مالیات بر ارزش افزوده اضافه شود'),
        ),
        migrations.AlterField(
            model_name='product',
            name='meta_keywords',
            field=models.CharField(blank=True, help_text='با کاما جدا کنید. (در هدر سایت برای سئو استفاده خواهد شد)', max_length=200, null=True, verbose_name='کلمات کلیدی'),
        ),
        migrations.AlterField(
            model_name='product',
            name='modify_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='modify date'),
        ),
        migrations.AlterField(
            model_name='product',
            name='release_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ انتشار'),
        ),
        migrations.AlterField(
            model_name='product',
            name='shipping_methods',
            field=models.ManyToManyField(to='eshop.shippingmethod', verbose_name='روش های ارسال'),
        ),
        migrations.AlterField(
            model_name='productproperty',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='create date'),
        ),
        migrations.AlterField(
            model_name='productproperty',
            name='modify_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='modify date'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='create date'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='has_value_added_tax',
            field=models.BooleanField(default=True, verbose_name='مالیات بر ارزش افزوده اضافه شود'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='modify_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='modify date'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='site_icon',
            field=models.ImageField(upload_to=main.tools.UploadToPathAndRename('setting'), verbose_name='آیکن سایت'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='soomasoft_webservice_password',
            field=models.CharField(default='', max_length=50, verbose_name='رمز وب سرویس سوماسافت'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='soomasoft_webservice_user',
            field=models.CharField(default='', max_length=50, verbose_name='کاربر وب سرویس سوماسافت'),
        ),
        migrations.AlterField(
            model_name='shippingcost',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='create date'),
        ),
        migrations.AlterField(
            model_name='shippingcost',
            name='modify_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='modify date'),
        ),
        migrations.AlterField(
            model_name='shippingmethod',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='create date'),
        ),
        migrations.AlterField(
            model_name='shippingmethod',
            name='modify_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='modify date'),
        ),
        migrations.AlterField(
            model_name='shippingstatus',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='create date'),
        ),
        migrations.AlterField(
            model_name='shippingstatus',
            name='modify_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='modify date'),
        ),
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='create date')),
                ('modify_date', models.DateTimeField(auto_now=True, null=True, verbose_name='modify date')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('title', models.CharField(max_length=100, verbose_name='address title')),
                ('receiver', models.CharField(max_length=100, verbose_name='receiver name and family')),
                ('phone', models.CharField(blank=True, max_length=30, null=True, verbose_name='phone')),
                ('city', models.CharField(max_length=100, verbose_name='شهر')),
                ('address', models.TextField(verbose_name='address')),
                ('postcode', models.CharField(max_length=10, validators=[eshop.validators.validate_postcode], verbose_name='postcode')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_theme.state', verbose_name='استان')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاریر')),
            ],
            options={
                'verbose_name': 'shipping address',
                'verbose_name_plural': 'shipping addresses',
            },
        ),
    ]
