# Generated by Django 4.2.2 on 2023-11-10 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0003_factor_factoritem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factor',
            name='payment_tracking_code',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='کد رهگیری پرداخت'),
        ),
    ]
