# Generated by Django 4.2.2 on 2023-10-31 14:06

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import eshop.validators
import main.tools


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eshop', '0003_alter_brand_create_date_alter_brand_modify_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='setting',
            options={'verbose_name': 'settings', 'verbose_name_plural': 'settings'},
        ),
        migrations.AlterModelOptions(
            name='shippingaddress',
            options={'verbose_name': 'آدرس ارسال', 'verbose_name_plural': 'آدرس های ارسال'},
        ),
        migrations.AlterField(
            model_name='cart',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AlterField(
            model_name='category',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='سفارش'),
        ),
        migrations.AlterField(
            model_name='product',
            name='meta_keywords',
            field=models.CharField(blank=True, help_text="separate with comma (used in the site's header for seo)", max_length=200, null=True, verbose_name='کلمات کلیدی'),
        ),
        migrations.AlterField(
            model_name='product',
            name='release_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='release date'),
        ),
        migrations.AlterField(
            model_name='product',
            name='shipping_methods',
            field=models.ManyToManyField(to='eshop.shippingmethod', verbose_name='shipping merthods'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='site_icon',
            field=models.ImageField(upload_to=main.tools.UploadToPathAndRename('setting'), verbose_name='site icon'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='site_logo',
            field=models.ImageField(upload_to=main.tools.UploadToPathAndRename('setting'), verbose_name='site logo'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='site_title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='site title'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='soomasoft_webservice_otp_number',
            field=models.CharField(default='', max_length=50, verbose_name='soomasoft otp number'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='soomasoft_webservice_password',
            field=models.CharField(default='', max_length=50, verbose_name='soomasoft web service password'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='soomasoft_webservice_user',
            field=models.CharField(default='', max_length=50, verbose_name='soomasoft web service user'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='value_added_tax_percent',
            field=models.PositiveIntegerField(default=9, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)], verbose_name='value added tax percent'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='address',
            field=models.TextField(verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='phone',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='شماره تماس'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='postcode',
            field=models.CharField(max_length=10, validators=[eshop.validators.validate_postcode], verbose_name='کد پستی'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='receiver',
            field=models.CharField(max_length=100, verbose_name='نام و نام خانوادگی گیرنده'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='title',
            field=models.CharField(max_length=100, verbose_name='عنوان آدرس'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
    ]
