# Generated by Django 4.2.2 on 2023-11-17 07:02

from django.db import migrations, models
import eshop.models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0004_alter_factor_payment_tracking_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Smsverificationcode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ایجاد')),
                ('modify_date', models.DateTimeField(auto_now=True, null=True, verbose_name='تاریخ ویرایش')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('sms_verification_uuid', models.CharField(default=eshop.models.create_uuid, max_length=48, verbose_name='کد تایید موبایل')),
                ('mobile', models.CharField(max_length=30, verbose_name='شماره همراه')),
                ('activation_code', models.PositiveIntegerField(verbose_name='کد فعالسازی')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
