# Generated by Django 4.2.7 on 2023-11-21 20:23

import django.core.validators
from django.db import migrations, models
import main.tools


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0005_smsverificationcode'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='setting',
            options={'verbose_name': 'settings', 'verbose_name_plural': 'settings'},
        ),
        migrations.AlterField(
            model_name='brand',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='create date'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='modify_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='modify date'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='create date'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='modify_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='modify date'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='create date'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='modify_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='modify date'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='create date'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='modify_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='modify date'),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='create date'),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='modify_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='modify date'),
        ),
        migrations.AlterField(
            model_name='factor',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='create date'),
        ),
        migrations.AlterField(
            model_name='factor',
            name='modify_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='modify date'),
        ),
        migrations.AlterField(
            model_name='factoritem',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='create date'),
        ),
        migrations.AlterField(
            model_name='factoritem',
            name='modify_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='modify date'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='create date'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='modify_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='modify date'),
        ),
        migrations.AlterField(
            model_name='paymentstatus',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='create date'),
        ),
        migrations.AlterField(
            model_name='paymentstatus',
            name='modify_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='modify date'),
        ),
        migrations.AlterField(
            model_name='product',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='create date'),
        ),
        migrations.AlterField(
            model_name='product',
            name='has_value_added_tax',
            field=models.BooleanField(default=False, verbose_name='مالیات بر ارزش افزوده اضافه شود'),
        ),
        migrations.AlterField(
            model_name='product',
            name='modify_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='modify date'),
        ),
        migrations.AlterField(
            model_name='productproperty',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='create date'),
        ),
        migrations.AlterField(
            model_name='productproperty',
            name='modify_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='modify date'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='create date'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='has_value_added_tax',
            field=models.BooleanField(default=True, verbose_name='مالیات بر ارزش افزوده اضافه شود'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='modify_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='modify date'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='site_icon',
            field=models.ImageField(upload_to=main.tools.UploadToPathAndRename('setting'), verbose_name='site icon'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='site_logo',
            field=models.ImageField(upload_to=main.tools.UploadToPathAndRename('setting'), verbose_name='site logo'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='site_title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='site title'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='soomasoft_webservice_otp_number',
            field=models.CharField(default='', max_length=50, verbose_name='soomasoft otp number'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='soomasoft_webservice_password',
            field=models.CharField(default='', max_length=50, verbose_name='soomasoft web service password'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='soomasoft_webservice_user',
            field=models.CharField(default='', max_length=50, verbose_name='soomasoft web service user'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='value_added_tax_percent',
            field=models.PositiveIntegerField(default=9, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)], verbose_name='value added tax percent'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='create date'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='modify_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='modify date'),
        ),
        migrations.AlterField(
            model_name='shippingcost',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='create date'),
        ),
        migrations.AlterField(
            model_name='shippingcost',
            name='modify_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='modify date'),
        ),
        migrations.AlterField(
            model_name='shippingmethod',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='create date'),
        ),
        migrations.AlterField(
            model_name='shippingmethod',
            name='modify_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='modify date'),
        ),
        migrations.AlterField(
            model_name='shippingstatus',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='create date'),
        ),
        migrations.AlterField(
            model_name='shippingstatus',
            name='modify_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='modify date'),
        ),
        migrations.AlterField(
            model_name='smsverificationcode',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='create date'),
        ),
        migrations.AlterField(
            model_name='smsverificationcode',
            name='modify_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='modify date'),
        ),
    ]
